import type { Student, PcoEvent } from './pco';
import { getUpcomingBirthdays } from './automations';

export const generateNewsletterDraft = (events: PcoEvent[], students: Student[]): string => {
    const today = new Date();

    // Sort events by date ascending (assuming attributes.starts_at exists, if not just list them)
    // PcoEvent interface in pco.ts has: attributes: { name: string }
    // Let's just list the events
    const upcomingEventsList = events.slice(0, 5).map(e => `- **${e.attributes.name}**: Join us for this upcoming event!`).join('\n');

    // Get birthdays for the next 7 days
    const upcomingBirthdays = getUpcomingBirthdays(students, 7, today);
    const birthdaysList = upcomingBirthdays.length > 0
        ? upcomingBirthdays.map(b => `- ${b.person.name} (Turning ${b.person.age + 1})`).join('\n')
        : 'No upcoming birthdays this week.';

    const draft = `
# 📬 Weekly Ministry Update

Welcome to our weekly newsletter! Here is what's happening in our community.

## 📅 Upcoming Events
${upcomingEventsList || 'Stay tuned for more upcoming events!'}

## 🎂 Upcoming Birthdays (Next 7 Days)
Let's celebrate with our community members who have birthdays this week:
${birthdaysList}

## 🙏 Prayer Focus
Please continue to pray for our community, our volunteers, and the upcoming services.

---
*Generated by Locus Newsletter Architect*
`.trim();

    return draft;
};
