import { isAfter, differenceInDays, parseISO, getDate, startOfDay } from 'date-fns';
import type { Student, PcoEvent } from './pco';

export interface NewsletterOptions {
    sermonTopic?: string;
    pastorNotes?: string;
}

export const generateNewsletter = (
    events: PcoEvent[],
    students: Student[],
    options?: NewsletterOptions,
    today: Date = new Date()
): string => {
    // 1. Find upcoming events (next 7 days)
    // Assuming events provided are active. We'll just list them if they exist.
    const upcomingEvents = events.slice(0, 5); // Just take a few for the newsletter

    // 2. Find upcoming birthdays (next 7 days)
    //
    // Adults only. A newsletter is a broadcast, and no household consents to a
    // minor's name and birthday appearing in one by virtue of being in the
    // directory. Three clauses are needed because no single one is trustworthy:
    //   - `isChild` is PCO's manually-maintained `child` flag, not derived, so a
    //     teenager whose record was never flagged reads as an adult.
    //   - `age < 18` catches those, but only when the birthdate is real.
    //   - `age > 110` catches placeholder birthdates (1900-01-01 and friends),
    //     which are valid dates that compute an implausible adult age and would
    //     otherwise clear the check above.
    // A plausible-but-wrong birthdate inside the adult range still slips
    // through; that is a data-quality problem, not one this filter can solve.
    const upcomingBirthdays = students
        .filter(s => s.birthdate && !s.isChild && s.age >= 18 && s.age <= 110)
        .map(person => {
            const birthdate = parseISO(person.birthdate);
            const birthdayThisYear = new Date(
                today.getFullYear(),
                birthdate.getMonth(),
                getDate(birthdate)
            );

            if (isAfter(today, birthdayThisYear) && differenceInDays(today, birthdayThisYear) > 0) {
                birthdayThisYear.setFullYear(today.getFullYear() + 1);
            }

            const daysUntil = differenceInDays(birthdayThisYear, startOfDay(today));
            return { person, daysUntil, date: birthdayThisYear };
        })
        .filter(b => b.daysUntil >= 0 && b.daysUntil <= 7)
        .sort((a, b) => a.daysUntil - b.daysUntil);

    // 3. Construct Markdown
    let md = `# Weekly Ministry Update\n\n`;

    if (options?.sermonTopic) {
        md += `## This Sunday: ${options.sermonTopic}\n\n`;
    }

    if (options?.pastorNotes) {
        md += `${options.pastorNotes}\n\n`;
    }

    md += `## 📅 Upcoming Events\n\n`;
    if (upcomingEvents.length > 0) {
        upcomingEvents.forEach(e => {
            md += `- **${e.attributes.name}**\n`;
        });
    } else {
        md += `*No major events scheduled for this week.*\n`;
    }
    md += `\n`;

    md += `## 🎂 Upcoming Birthdays\n\n`;
    if (upcomingBirthdays.length > 0) {
        upcomingBirthdays.forEach(b => {
            const dateStr = b.date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
            md += `- ${b.person.name} (${dateStr})\n`;
        });
    } else {
        md += `*No birthdays in the next 7 days.*\n`;
    }
    md += `\n`;

    md += `---\n*Generated by Locus Pastoral Co-Pilot*`;

    return md;
};
