import { isAfter, differenceInDays, parseISO, getDate, startOfDay } from 'date-fns';
import type { Student, PcoEvent } from './pco';

export interface NewsletterOptions {
    sermonTopic?: string;
    pastorNotes?: string;
}

export const generateNewsletter = (
    events: PcoEvent[],
    students: Student[],
    options?: NewsletterOptions,
    today: Date = new Date()
): string => {
    // 1. Find upcoming events (next 7 days)
    // Assuming events provided are active. We'll just list them if they exist.
    const upcomingEvents = events.slice(0, 5); // Just take a few for the newsletter

    // 2. Find upcoming birthdays (next 7 days)
    const upcomingBirthdays = students
        .filter(s => s.birthdate)
        .map(person => {
            const birthdate = parseISO(person.birthdate);
            const birthdayThisYear = new Date(
                today.getFullYear(),
                birthdate.getMonth(),
                getDate(birthdate)
            );

            if (isAfter(today, birthdayThisYear) && differenceInDays(today, birthdayThisYear) > 0) {
                birthdayThisYear.setFullYear(today.getFullYear() + 1);
            }

            const daysUntil = differenceInDays(birthdayThisYear, startOfDay(today));
            return { person, daysUntil, date: birthdayThisYear };
        })
        .filter(b => b.daysUntil >= 0 && b.daysUntil <= 7)
        .sort((a, b) => a.daysUntil - b.daysUntil);

    // 3. Construct Markdown
    let md = `# Weekly Ministry Update\n\n`;

    if (options?.sermonTopic) {
        md += `## This Sunday: ${options.sermonTopic}\n\n`;
    }

    if (options?.pastorNotes) {
        md += `${options.pastorNotes}\n\n`;
    }

    md += `## 📅 Upcoming Events\n\n`;
    if (upcomingEvents.length > 0) {
        upcomingEvents.forEach(e => {
            md += `- **${e.attributes.name}**\n`;
        });
    } else {
        md += `*No major events scheduled for this week.*\n`;
    }
    md += `\n`;

    md += `## 🎂 Upcoming Birthdays\n\n`;
    if (upcomingBirthdays.length > 0) {
        upcomingBirthdays.forEach(b => {
            const dateStr = b.date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
            md += `- ${b.person.name} (${dateStr})\n`;
        });
    } else {
        md += `*No birthdays in the next 7 days.*\n`;
    }
    md += `\n`;

    md += `---\n*Generated by Locus Pastoral Co-Pilot*`;

    return md;
};
